Add an RPC deleteAllPendingTransactions()
CodeChain-io/codechain-rpc-js pull request #11
Opened 2020-01-06 07:35 UTC by junha1

2020-01-08 11:59 UTC, joojis requested changes
Would you add a test?

2020-01-09 01:05 UTC, junha1 commented
@joojis I added.

2020-01-09 05:01 UTC, joojis commented
@junha1 I think you need to update the docker tag here too.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/9711879/72039462-91e92a80-32e8-11ea-811f-e95380892ba7.png">

2020-01-09 10:58 UTC, joojis approved these changes

2020-01-09 10:58 UTC, merged